image: node:alpine

variables:
  PUBLIC_URL: "/escohotado"

cache:
  paths:
  - todo-list-client-react/node_modules

stages:
- deploy

pages:
  stage: deploy
  script:
    - cd todo-list-client-react/
    - yarn
    - yarn build --prod
    - mv build ../public
    - cp ../public/index.html ../public/404.html
  artifacts:
    paths:
    - public
  only:
    - master